apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ include "tensor-fusion.namespace" . }}
  labels:
    tensor-fusion.ai/component: config
    {{- include "tensor-fusion.labels" . | nindent 4 }}
data:
  # Read by tensor fusion operator, eval alert rules and send to alertmanager if enabledAlert is true
  config.yaml: |
    {{- toYaml .Values.dynamicConfig | nindent 4 }}
  scheduler-config.yaml: |
    {{- toYaml .Values.schedulerConfig | nindent 4 }}
    