apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-controller
  namespace: {{ include "tensor-fusion.namespace" . }}
  labels:
    {{- include "tensor-fusion.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tensor-fusion.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "tensor-fusion.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: controller
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tensor-fusion.serviceAccountName" . }}
      containers:
        - name: controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          livenessProbe:
            {{- toYaml .Values.controller.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.controller.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          volumeMounts:
            - name: cert
              readOnly: true
              mountPath: /tmp/k8s-webhook-server/serving-certs
            - name: config
              mountPath: /etc/tensor-fusion
      volumes:
        - name: cert
          secret:
            secretName: {{.Values.controller.admissionWebhooks.secretName}}
            defaultMode: 420
        - name: config
          configMap:
            name: {{ include "tensor-fusion.fullname" . }}-config
            defaultMode: 420
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
