{{- if .Values.greptime.isCloud }}
apiVersion: v1
kind: Secret
metadata:
  name: tf-greptimedb-secret
  namespace: {{ include "tensor-fusion.namespace" . }}
data:
  password: "{{ .Values.greptime.password | b64enc }}"
{{- end }}