{{- if .Values.greptime.installStandalone }}
# NOTICE: make sure greptimedb operator had been installed in your test cluster
# cloud mode is recommended to reduce the maintenance effort
# ```bash
# helm repo add greptime https://greptimeteam.github.io/helm-charts/
# helm repo update
# helm install greptimedb-operator greptime/greptimedb-operator -n greptimedb --create-namespace
# ```
apiVersion: greptime.io/v1alpha1
kind: GreptimeDBStandalone
metadata:
  name: greptimedb
  namespace: greptimedb
spec:
  base:
    main:
      image: docker.io/greptime/greptimedb:latest
      livenessProbe:
        failureThreshold: 10
        httpGet:
          path: /health
          port: 4000
        periodSeconds: 5
      readinessProbe:
        failureThreshold: 10
        httpGet:
          path: /health
          port: 4000
        periodSeconds: 5
      resources: {}
      startupProbe:
        failureThreshold: 60
        httpGet:
          path: /health
          port: 4000
        periodSeconds: 5
  datanodeStorage:
    dataHome: /data/greptimedb
    fs:
      mountPath: /data/greptimedb
      name: datanode
      storageRetainPolicy: Retain
      storageSize: 20Gi
  httpPort: 4000
  logging:
    format: text
    level: info
    logsDir: /data/greptimedb/logs
    onlyLogToStdout: false
    persistentWithData: false
  mysqlPort: 4002
  postgreSQLPort: 4003
  rollingUpdate:
    maxUnavailable: 1
    partition: 0
  rpcPort: 4001
  service:
    type: ClusterIP
  version: latest
{{- end }}
