apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tensor-fusion.ai
  resources:
  - gpunodeclasses
  - gpunodes
  - gpupools
  - gpus
  - schedulingconfigtemplates
  - tensorfusionclusters
  - tensorfusionconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tensor-fusion.ai
  resources:
  - gpunodeclasses/finalizers
  - gpunodes/finalizers
  - gpupools/finalizers
  - gpus/finalizers
  - schedulingconfigtemplates/finalizers
  - tensorfusionclusters/finalizers
  - tensorfusionconnections/finalizers
  verbs:
  - update
- apiGroups:
  - tensor-fusion.ai
  resources:
  - gpunodeclasses/status
  - gpunodes/status
  - gpupools/status
  - gpus/status
  - schedulingconfigtemplates/status
  - tensorfusionclusters/status
  - tensorfusionconnections/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tensor-fusion.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "tensor-fusion.serviceAccountName" . }}
  namespace: {{ include "tensor-fusion.namespace" . }}
