apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tensor-fusion-hypervisor-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
