apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-role
rules:
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/finalizers
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - nodes/status
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tensor-fusion.ai
  resources:
  - workloadprofiles
  - gpunodeclasses
  - gpunodes
  - gpupools
  - gpus
  - schedulingconfigtemplates
  - tensorfusionclusters
  - tensorfusionconnections
  - tensorfusionworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tensor-fusion.ai
  resources:
  - workloadprofiles/finalizers
  - gpunodeclasses/finalizers
  - gpunodes/finalizers
  - gpupools/finalizers
  - gpus/finalizers
  - schedulingconfigtemplates/finalizers
  - tensorfusionclusters/finalizers
  - tensorfusionconnections/finalizers
  - tensorfusionworkloads/finalizers
  verbs:
  - update
- apiGroups:
  - tensor-fusion.ai
  resources:
  - workloadprofiles/status
  - gpunodeclasses/status
  - gpunodes/status
  - gpupools/status
  - gpus/status
  - schedulingconfigtemplates/status
  - tensorfusionclusters/status
  - tensorfusionconnections/status
  - tensorfusionworkloads/status
  verbs:
  - get
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tensor-fusion.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "tensor-fusion.serviceAccountName" . }}
  namespace: {{ include "tensor-fusion.namespace" . }}