apiVersion: v1
kind: ServiceAccount
metadata:
  # Service account for watch vGPU worker auto scaling event and collect Pod log metadata
  # The name is fixed and only needs pods/nodes read permission
  name: tensor-fusion-hypervisor-sa
  namespace: {{ include "tensor-fusion.namespace" . }}
  labels:
    {{- include "tensor-fusion.labels" . | nindent 4 }}
automountServiceAccountToken: true