apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-vector-config
  namespace: {{ include "tensor-fusion.namespace" . }}
data:
  vector-operator.yaml: |
    api:
      enabled: true
    sources:
      metrics:
        type: file
        data_dir: /logs
        include:
          - /logs/metrics*.log

      kubernetes_logs:
        type: kubernetes_logs
        self_node_name: "${NODE_NAME}"
        extra_label_selector: "tensor-fusion.ai/component in (operator)"

    transforms:
      parse_influx:
        type: remap
        inputs:
          - metrics
        source: |
          . = parse_influxdb!(.message)
      prepare_metrics:
        type: remap
        inputs:
          - parse_influx
        source: |
          .namespace = "tf"
          .tags.nodeName = "${NODE_NAME}"
      
      log_to_metric:
        type: log_to_metric
        inputs:
          - prepare_metrics
        all_metrics: true
        metrics: []

      prepare_kubernetes_logs:
        type: remap
        inputs:
          - kubernetes_logs
        source: |
          .message = .message
          .container = .kubernetes.container_name
          .pod = .kubernetes.pod_name
          .namespace = .kubernetes.pod_namespace
          .component = .kubernetes.pod_labels."tensor-fusion.ai/component"
          del(.kubernetes)
          del(.file)
          del(.source_type)
    sinks:
      sink_greptimedb_operator_metrics:
        type: greptimedb_metrics
        inputs:
          - log_to_metric
        new_naming: false
        endpoint: {{ .Values.greptime.host }}:{{ .Values.greptime.port }}
        {{- if eq .Values.greptime.isCloud true }}
        dbname: {{ .Values.greptime.db }}
        username: {{ .Values.greptime.user }}
        password: {{ .Values.greptime.password }}
        tls: {}
        {{- end }}
      
      sink_greptimedb_operator_logs:
        type: greptimedb_logs
        compression: gzip
        table: tf_system_log
        inputs:
          - prepare_kubernetes_logs
        {{- if ne .Values.greptime.isCloud true }}
        endpoint: http://{{ .Values.greptime.host }}:4000
        dbname: public
        {{- else }}
        endpoint: https://{{ .Values.greptime.host }}
        dbname: {{ .Values.greptime.db }}
        username: {{ .Values.greptime.user }}
        password: {{ .Values.greptime.password }}
        {{- end }}

  vector-hypervisor.yaml: |
    api:
      enabled: true
    
    sources:
      kubernetes_logs:
        type: kubernetes_logs
        self_node_name: "${NODE_NAME}"
        extra_label_selector: "tensor-fusion.ai/component in (hypervisor,worker)"
      metrics:
        type: file
        data_dir: /logs
        include:
          - /logs/metrics.log.*
    transforms:
      parse_influx:
        type: remap
        inputs:
          - metrics
        source: |
          . = parse_influxdb!(.message)
      prepare_metrics:
        type: remap
        inputs:
          - parse_influx
        source: |
          .namespace = "tf"
          .tags.nodeName = "${NODE_NAME}"
      
      log_to_metric:
        type: log_to_metric
        inputs:
          - prepare_metrics
        all_metrics: true
        metrics: []

      prepare_kubernetes_logs:
        type: remap
        inputs:
          - kubernetes_logs
        source: |
          .message = .message
          .container = .kubernetes.container_name
          .pod = .kubernetes.pod_name
          .namespace = .kubernetes.pod_namespace
          .component = .kubernetes.pod_labels."tensor-fusion.ai/component"
          del(.kubernetes)
          del(.file)
          del(.source_type)

    sinks:
      sink_greptimedb_hypervisor_metrics:
        type: greptimedb_metrics
        inputs:
          - log_to_metric
        new_naming: false
        endpoint: {{ .Values.greptime.host }}:{{ .Values.greptime.port }}
        {{- if eq .Values.greptime.isCloud true }}
        dbname: {{ .Values.greptime.db }}
        username: {{ .Values.greptime.user }}
        password: {{ .Values.greptime.password }}
        tls: {}
        {{- end }}
      sink_greptimedb_hypervisor_worker_logs:
        type: greptimedb_logs
        compression: gzip
        table: tf_system_log
        inputs:
          - prepare_kubernetes_logs
        {{- if ne .Values.greptime.isCloud true }}
        endpoint: http://{{ .Values.greptime.host }}:4000
        dbname: public
        {{- else }}
        endpoint: https://{{ .Values.greptime.host }}
        dbname: {{ .Values.greptime.db }}
        username: {{ .Values.greptime.user }}
        password: {{ .Values.greptime.password }}
        {{- end }}
