apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-vector-config
  namespace: {{ include "tensor-fusion.namespace" . }}
data:
  vector-operator.yaml: |
    api:
      enabled: true
    sources:
      controller_metrics:
        type: prometheus_scrape
        endpoints:
          - http://localhost:9000/metrics
    transforms:
      prepare_controller_metrics:
        type: remap
        inputs: 
          - controller_metrics
        source: |
          .namespace = "tf"
    sinks:
      sink_greptimedb_controller_metrics:
        type: prometheus_remote_write
        inputs:
          - prepare_controller_metrics
        {{- if ne .Values.greptime.isCloud true }}
        endpoint: http://{{ .Values.greptime.host }}:4000/v1/prometheus/write?db=public
        {{- else }}
        endpoint: https://{{ .Values.greptime.host }}/v1/prometheus/write?db={{ .Values.greptime.db }}
        auth:
          strategy: basic
          user: {{ .Values.greptime.user }}
          password: {{ .Values.greptime.password }}
        {{- end }}

  vector-hypervisor.yaml: |
    api:
      enabled: true
    
    sources:
      metrics:
        type: file
        data_dir: /logs
        include:
          - /logs/metrics.log
      
    transforms:
      parse_influx:
        type: remap
        inputs:
          - metrics
        source: |
          . = parse_influxdb!(.message)
      prepare_metrics:
        type: remap
        inputs:
          - parse_influx
        source: |
          .namespace = "tf"
          .tags.nodeName = "${NODE_NAME}"
      
      log_to_metric:
        type: log_to_metric
        inputs:
          - prepare_metrics
        all_metrics: true
        metrics: []

    sinks:
      sink_greptimedb_hypervisor_metrics:
        type: greptimedb_metrics
        inputs:
          - log_to_metric
        new_naming: false
        endpoint: {{ .Values.greptime.host }}:{{ .Values.greptime.port }}
        {{- if eq .Values.greptime.isCloud true }}
        dbname: {{ .Values.greptime.db }}
        username: {{ .Values.greptime.user }}
        password: {{ .Values.greptime.password }}
        tls: {}
        {{- end }}

