
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "k8s.io/*"
      - dependency-name: "sigs.k8s.io/*"
      - dependency-name: "sigs.k8s.io/karpenter*"
    open-pull-requests-limit: 3
    assignees:
      - "code2life"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "deps"
      include: "scope"