# permissions for end users to view clientprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tensor-fusion-operator
    app.kubernetes.io/managed-by: kustomize
  name: clientprofile-viewer-role
rules:
- apiGroups:
  - tensor-fusion.ai
  resources:
  - clientprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tensor-fusion.ai
  resources:
  - clientprofiles/status
  verbs:
  - get
