# permissions for end users to view gpus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tensor-fusion
    app.kubernetes.io/managed-by: kustomize
  name: gpu-viewer-role
rules:
- apiGroups:
  - tensor-fusion.ai
  resources:
  - gpus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tensor-fusion.ai
  resources:
  - gpus/status
  verbs:
  - get
