# This rule is not used by the project tensor-fusion itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over tensor-fusion.ai.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tensor-fusion
    app.kubernetes.io/managed-by: kustomize
  name: gpunodeclaim-admin-role
rules:
- apiGroups:
  - tensor-fusion.ai
  resources:
  - gpunodeclaims
  verbs:
  - '*'
- apiGroups:
  - tensor-fusion.ai
  resources:
  - gpunodeclaims/status
  verbs:
  - get
