# permissions for end users to view tensorfusionconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tensor-fusion
    app.kubernetes.io/managed-by: kustomize
  name: tensorfusionconnection-viewer-role
rules:
- apiGroups:
  - tensor-fusion.ai
  resources:
  - tensorfusionconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tensor-fusion.ai
  resources:
  - tensorfusionconnections/status
  verbs:
  - get
