# permissions for end users to view tensorfusionclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tensor-fusion-operator
    app.kubernetes.io/managed-by: kustomize
  name: tensorfusioncluster-viewer-role
rules:
- apiGroups:
  - tensor-fusion.ai
  resources:
  - tensorfusionclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tensor-fusion.ai
  resources:
  - tensorfusionclusters/status
  verbs:
  - get
