apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: $HOME/.kube/config
profiles:
# Refer: https://kubernetes.io/docs/reference/scheduling/config/
- schedulerName: tensor-fusion-scheduler
  plugins:
    filter:
      enabled:
      - name: GPUResourceFit
      - name: GPUNetworkTopologyAware
    score:
      enabled:
      - name: GPUResourceFit
        weight: 5
      - name: GPUNetworkTopologyAware
        weight: 7
  pluginConfig:
  - name: GPUResourceFit
    args:
      maxWorkerPerNode: 256
  - name: GPUNetworkTopologyAware
    args:
      # Avoid the remote TFWorker RX/TX to avoid single node consume too much bandwidth
      # Need enable monitor to take effect
      totalIntranetBandWidthGBps: 100
  - name: NodeResourcesFit
    args:
      scoringStrategy:
        resources:
        - name: cpu
          weight: 1
        - name: memory
          weight: 1
        requestedToCapacityRatio:
          shape:
          - utilization: 0
            score: 0
          - utilization: 80
            score: 10
          - utilization: 90
            score: 1
          - utilization: 100
            score: 0
        type: RequestedToCapacityRatio

