apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-webhook-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tensor-fusion.fullname" . }}-webhook-job
subjects:
  - kind: ServiceAccount
    name: {{ include "tensor-fusion.fullname" . }}-webhook-job
    namespace: {{ include "tensor-fusion.namespace" . }}