apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-mutating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "tensor-fusion.fullname" . }}-webhook
      namespace: {{ include "tensor-fusion.namespace" . }}
      path: /mutate-v1-pod
  failurePolicy: Fail
  name: mpod-v1.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
  objectSelector:
    matchExpressions:
      - key: tensor-fusion.ai/enabled
        operator: In
        values:
          - "true"
