apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-webhook-job
  namespace: {{ include "tensor-fusion.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"
