apiVersion: v1
kind: Service
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-webhook
  namespace: {{ include "tensor-fusion.namespace" . }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "tensor-fusion.controller.selectorLabels" . | nindent 6 }}