name: Release Helm Chart

on:
  push:
    branches: [ dev-helm-release ]
    paths: [ 'charts/**' ]
  release:
    types: [published]

jobs:
  update-chart-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Helm Package
      uses: alpine/helm@v3
      with:
        command: package charts/ -d gh-pages/

    - name: Helm Index
      uses: alpine/helm@v3
      working-directory: gh-pages
      with:
        command: repo index . --url https://helm.tensor-fusion.ai/

    - name: Commit and Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update Helm chart"
        git push

  release-asset:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [update-chart-repo]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Helm Package
      uses: alpine/helm@v3
      with:
        command: package charts/ -d release/

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./release/*.tgz
        asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.tgz
        asset_content_type: application/gzip